[trace]
entry = "main.py"
include = [
    "physics_example_project.world.World",
    "physics_example_project.particle.PointMass",
    "physics_example_project.particle.RigidBody",
    "physics_example_project.force.ConstantForce",
    "physics_example_project.force.SpringForce",
]
exclude_methods = []

[class_diagram]
out = "diagrams/"
stubs = "qualified"
