[trace]
entry = "main.py"
include = [
    "physics.world.World",
    "physics.particle.PointMass",
    "physics.particle.RigidBody",
    "physics.force.ConstantForce",
    "physics.force.SpringForce",
]
exclude_methods = []

[class_diagram]
out = "diagrams/"
stubs = "qualified"
